-- Generated by BAR Scenario Designer. Place in singleplayer/scenarios/.
local scenariodata = {
	index = 26,
	scenarioid = "new_scenario",
	version = "1",
	title = "New Scenario",
	author = "local mod",
	imagepath = "scenario26.jpg",
	imageflavor = "",
	summary = "",
	briefing = "",
	mapfilename = "Center Command BAR v1.0",
	playerstartx = "15%",
	playerstarty = "50%",
	partime = 3000, parresources = 1000000,
	difficulty = 4, defaultdifficulty = "Normal",
	difficulties = {
		{name = "Beginner", playerhandicap = 50, enemyhandicap = 0},
		{name = "Normal",   playerhandicap = 0,  enemyhandicap = 0},
		{name = "Hard",     playerhandicap = 0,  enemyhandicap = 25},
	},
	allowedsides = {"Armada", "Cortex", "Random"},
	victorycondition = "Complete the scripted objectives",
	losscondition = "Death of your Commander",
	unitlimits = {},
	scenariooptions = { scenarioid = "new_scenario" },
	startscript = [[[Game]
{
	[allyTeam0] { startrectleft = 0; startrectright = 0.25; startrecttop = 0; startrectbottom = 1; numallies = 0; }
	[allyTeam1] { startrectleft = 0.75; startrectright = 1; startrecttop = 0; startrectbottom = 1; numallies = 0; }
	[team0] { Side = __PLAYERSIDE__; Handicap = __PLAYERHANDICAP__; RgbColor = 0 0.51 0.78; AllyTeam = 0; TeamLeader = 0; StartPosX = 1229; StartPosZ = 2048; }
	[team1] { Side = Armada; Handicap = __ENEMYHANDICAP__; RgbColor = 0.9 0.1 0.29; AllyTeam = 1; TeamLeader = 0; StartPosX = 2808; StartPosZ = 2025; }
	[team2] { Side = Armada; Handicap = __ENEMYHANDICAP__; RgbColor = 0.9 0.1 0.29; AllyTeam = 1; TeamLeader = 0; StartPosX = 5553; StartPosZ = 1987; }
	[team3] { Side = Armada; Handicap = __ENEMYHANDICAP__; RgbColor = 0.9 0.1 0.29; AllyTeam = 1; TeamLeader = 0; StartPosX = 7019; StartPosZ = 2007; }
	[ai0] { Host = 0; IsFromDemo = 0; Name = BARbarianAI(1); ShortName = BARb; Team = 1; Version = stable; }
	[ai1] { Host = 0; IsFromDemo = 0; Name = BARbarianAI(2); ShortName = BARb; Team = 2; Version = stable; }
	[ai2] { Host = 0; IsFromDemo = 0; Name = BARbarianAI(3); ShortName = BARb; Team = 3; Version = stable; }
	[modoptions] { scenariooptions = __SCENARIOOPTIONS__; mission_path = missions/center_command_bar_v1_0_missionxx.lua; mission_difficulty = normal; deathmode = com; }
	[player0] { IsFromDemo = 0; Name = __PLAYERNAME__; Team = 0; rank = 0; }
	hostip = 127.0.0.1; hostport = 0; numplayers = 1; startpostype = 0;
	mapname = __MAPNAME__; ishost = 1; numusers = 4; gametype = __BARVERSION__;
	GameStartDelay = 3; myplayername = __PLAYERNAME__; nohelperais = 0;
	NumRestrictions = __NUMRESTRICTIONS__;
	[RESTRICT] { __RESTRICTEDUNITS__ }
}
	]],
}
return scenariodata