--------------------------------------------------------------------------------
-- mapinfo.lua  -- generated by BAR map_extender (diffuse-only derivative)
-- SSMF overlays (normal/spec/splat) intentionally omitted; the map renders from
-- the recomposed .smt diffuse. Geometry is real and playable. See README.md.
--------------------------------------------------------------------------------

local mapinfo = {
	name        = "@@NAME@@",
	shortname   = "@@NAME@@",
	description = "Recomposed map (map_extender PoC)",
	author      = "map_extender",
	version     = "@@VERSION@@",
	modtype     = 3, --// 3=map
	depend      = {"Map Helper v1"},
	replace     = {},

	maphardness     = 120,
	notDeformable   = false,
	gravity         = 100,
	tidalStrength   = 0,
	maxMetal        = 2.1,
	extractorRadius = 20,
	voidWater       = false,
	autoShowMetal   = true,

	smf = {
		minheight = @@MINH@@,
		maxheight = @@MAXH@@,
	},

	sound = { preset = "default" },

	lighting = {
		groundShadowDensity = 0.75,
		unitShadowDensity   = 0.75,
		groundAmbientColor  = {0.6, 0.6, 0.6},
		groundDiffuseColor  = {0.9, 0.9, 0.9},
		groundSpecularColor = {0.1, 0.1, 0.1},
		sunDir              = {0.8, 1.0, -0.7},
		specularsuncolor    = {0.6, 0.6, 0.6},
		unitAmbientColor    = {0.75, 0.75, 0.75},
		unitDiffuseColor    = {1.0, 1.0, 1.0},
		unitSpecularColor   = {0.4, 0.4, 0.5},
	},

	water = {
		damage    = 0,
		absorb    = {0.08, 0.01, 0.0025},
		basecolor = {0.2, 1.2, 0.7},
		mincolor  = {0.0, 0.2, 0.2},
		hasWaterPlane = false,
	},

	teams = {
@@TEAMS@@
	},

	terrainTypes = {
		[0]   = { name = "rock",  hardness = 4, receiveTracks = true,
			moveSpeeds = { tank = 1, kbot = 1, hover = 1, ship = 1 } },
		[255] = { name = "cliff", hardness = 4, receiveTracks = true,
			moveSpeeds = { tank = 1, kbot = 1, hover = 1, ship = 1 } },
	},
}

--------------------------------------------------------------------------------
local function lowerkeys(ta)
	local fix = {}
	for i, v in pairs(ta) do
		if type(i) == "string" and i ~= i:lower() then fix[#fix+1] = i end
		if type(v) == "table" then lowerkeys(v) end
	end
	for i = 1, #fix do local idx = fix[i]; ta[idx:lower()] = ta[idx]; ta[idx] = nil end
end
lowerkeys(mapinfo)
return mapinfo
