-- New Scenario  -- generated by BAR Scenario Designer
-- Map: Seths Ravine Remake 1.3.1  (8192x6144)
-- Edit/iterate in-game with /luarules reload (logic-only changes).
--[==[ SCENARIO_DESIGNER_V1
{"v":1,"map":{"file":"seths_ravine_remake_1.3.1.sd7","name":"Seths Ravine Remake 1.3.1","w":8192,"h":6144,"thumb":"maps/seths_ravine_remake_1.3.1.jpg"},"meta":{"title":"New Scenario","author":"","summary":"","briefing":"","difficulty":"normal","missionFile":"seths_ravine_remake_1_3_1_mission","scenarioIndex":26},"playerStart":{"x":3089,"z":3922},"aiStarts":[{"x":5586,"z":3758}],"aiCount":1,"freeze":["ai1"],"buildings":[{"id":"e3","def":"cormoho","x":6153,"z":4897,"facing":"","role":"enemies"},{"id":"e4","def":"cormoho","x":5830,"z":5189,"facing":"","role":"enemies"},{"id":"e5","def":"cormoho","x":6267,"z":5381,"facing":"","role":"enemies"},{"id":"e6","def":"cormoho","x":6824,"z":5116,"facing":"","role":"enemies"},{"id":"e7","def":"cormoho","x":6569,"z":4695,"facing":"","role":"enemies"},{"id":"e8","def":"cormoho","x":7146,"z":4544,"facing":"","role":"enemies"},{"id":"e9","def":"corlab","x":5727,"z":3682,"facing":"","role":"enemies"},{"id":"e10","def":"corhlt","x":5733,"z":3851,"facing":"","role":"enemies"},{"id":"e11","def":"corhlt","x":5733,"z":3517,"facing":"","role":"enemies"}],"triggers":[{"kind":"trigger","id":"e12","name":"Unit entered area","type":"UnitEnteredLocation","settings":{"repeating":false},"params":{"team":"humans","radius":381,"x":3676,"z":3947,"onlyCommander":true},"actions":["e1"]},{"kind":"trigger","id":"e13","name":"Unit entered area 2","type":"UnitEnteredLocation","settings":{"repeating":false},"params":{"team":"humans","radius":312,"x":5274,"z":3413},"actions":["e14"]}],"actions":[{"kind":"action","id":"e1","name":"Spawn units","type":"SpawnUnits","params":{"quantity":5,"team":"enemies","x":4137,"z":3848,"unitDefName":"cormort"}},{"kind":"action","id":"e14","name":"Unfreeze team","type":"UnfreezeTeam","params":{"team":"enemies"}}],"nextId":15}
]==]

local triggerTypes = GG['MissionAPI'].TriggerTypes
local actionTypes  = GG['MissionAPI'].ActionTypes

local Teams = { humans = { allyTeam = 0 }, enemies = { allyTeam = 1 } }

local Setup = {
	freeze = { "ai1" },
	startPositions = {
		{ role = "humans", x = 3089, z = 3922 },
		{ role = "ai1", x = 5586, z = 3758 },
	},
	bases = {
		enemies = {
			{ def = "cormoho", x = 6153, z = 4897 },
			{ def = "cormoho", x = 5830, z = 5189 },
			{ def = "cormoho", x = 6267, z = 5381 },
			{ def = "cormoho", x = 6824, z = 5116 },
			{ def = "cormoho", x = 6569, z = 4695 },
			{ def = "cormoho", x = 7146, z = 4544 },
			{ def = "corlab", x = 5727, z = 3682 },
			{ def = "corhlt", x = 5733, z = 3851 },
			{ def = "corhlt", x = 5733, z = 3517 },
		},
	},
}

local Triggers = {
	Unitenteredarea = {
		type = triggerTypes.UnitEnteredLocation,
		settings = { repeating = false },
		parameters = { team = "humans", onlyCommander = true, x = 3676, z = 3947, radius = 381 },
		actions = { "Spawnunits" },
	},
	Unitenteredarea2 = {
		type = triggerTypes.UnitEnteredLocation,
		settings = { repeating = false },
		parameters = { team = "humans", x = 5274, z = 3413, radius = 312 },
		actions = { "Unfreezeteam" },
	},
}

local Actions = {
	Spawnunits = {
		type = actionTypes.SpawnUnits,
		parameters = { unitDefName = "cormort", quantity = 5, x = 4137, z = 3848, team = "enemies" },
	},
	Unfreezeteam = {
		type = actionTypes.UnfreezeTeam,
		parameters = { team = "enemies" },
	},
}

return { Teams = Teams, Setup = Setup, Triggers = Triggers, Actions = Actions }
